import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import atakirk from "../public/atakirk.png";
import atakirk2 from "../public/atakirk2.png";
import atakirk3 from "../public/atakirk3.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Atakirk Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-purple-400">
              developed by atakirk
            </h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode((prev) => !prev)}
                    className="cursor-pointer text-2xl text-purple-400"
                  />
                ) : (
                  <BsFillSunFill
                    onClick={() => setDarkMode((prev) => !prev)}
                    className="cursor-pointer text-2xl text-yellow-500"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-bl from-purple-900 to-purple-400 text-white px-4 py-2 ml-8 rounded-md"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-purple-700 font-medium md:text-6xl dark:text-purple-600">
              Ataberk Yavuzyaşar
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Engineer and Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300">
              Computer Scientist providing services for Front-End Development.
              Check below for more details!
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-purple-800">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          <div className="relative bg-gradient-to-b mx-auto from-purple-800 rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96">
            <Image src={atakirk3} />
          </div>
        </section>

        <section className="mt-10 ">
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-100">
              Services I offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-600 dark:text-gray-300">
              Since the beginning of my journey as a{" "}
              <span className="text-purple-700">Computer Scientist</span> and{" "}
              <span className="text-purple-700">Front-End Developer</span>, I've
              done lots of project and worked several companies. Also
              collaborated with talented people to create digital products for
              both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-600 dark:text-gray-300">
              {" "}
              I offer from a wide range of services, including{" "}
              <span className="text-purple-700">programming</span> and{" "}
              <span className="text-purple-700">teaching</span>
            </p>
          </div>

          <div className="lg:flex gap-10 dark:text-gray-300">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-purple-700">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-gray-300">
                Photoshop
              </p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">
                Illustrator
              </p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Well-Prepared Web Products
              </h3>
              <p className="py-2">
                Creating a well-prepared web projects for your needs.
              </p>
              <h4 className="py-4 text-purple-700">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-gray-300">React.js</p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">Node.js</p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">Next.js</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Informative Courses
              </h3>
              <p className="py-2">
                If you want to learn Front-End Development or Computer Science
                Fundementals, this one is for you.
              </p>
              <h4 className="py-4 text-purple-700">Design tools I use</h4>
              <p className=" text-gray-800 py-1 dark:text-gray-300">Zoom</p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">replit</p>
              <p className=" text-gray-800 py-1 dark:text-gray-300">VSC</p>
            </div>
          </div>
        </section>
        <section>
          <div className="dark:text-gray-300">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-600 dark:text-gray-300">
              Since the beginning of my journey as a{" "}
              <span className="text-purple-700">Computer Scientist</span> and{" "}
              <span className="text-purple-700">Front-End Developer</span>, I've
              done lots of project and worked several companies. Also
              collaborated with talented people to create digital products for
              both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-600 dark:text-gray-300">
              {" "}
              I offer from a wide range of services, including{" "}
              <span className="text-purple-700">programming</span> and{" "}
              <span className="text-purple-700">teaching.</span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "fill", minHeight: "100%" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "fill", minHeight: "100%" }}
              />
            </div>
            <div className="basis-1/3 flex-1">
              {" "}
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                style={{ layout: "responsive" }}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
